-- Starter outbox queue (com.kholodilin). Not a reuse of V2 outbox_events:
-- that table stays as Flyway history and is no longer written to.
-- Parent + outbox_records_active (status < 100) / outbox_records_archive (status >= 100).

CREATE TABLE outbox_records (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    aggregate_id    VARCHAR(128)  NOT NULL,
    partition_key   VARCHAR(128)  NOT NULL,
    event_type      VARCHAR(128)  NOT NULL,
    payload         JSONB         NOT NULL,
    headers         JSONB,
    status          INT           NOT NULL,
    retry_count     INT           NOT NULL DEFAULT 0,
    locked_by       VARCHAR(128),
    locked_until    TIMESTAMPTZ,
    trace_parent    TEXT,
    sent_at         TIMESTAMPTZ,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    PRIMARY KEY (status, id)
) PARTITION BY RANGE (status);

CREATE TABLE outbox_records_active
    PARTITION OF outbox_records
    FOR VALUES FROM (MINVALUE) TO (100);

CREATE TABLE outbox_records_archive
    PARTITION OF outbox_records
    FOR VALUES FROM (100) TO (MAXVALUE);

CREATE INDEX idx_outbox_records_status_locked_until
    ON outbox_records (status, locked_until);
